### PR TITLE
Added keyboard and click events

### PR DESCRIPTION
**Pull request by up730418**
#986 
Implemented new listeners to create the desired functionality

### CODE REVIEW

**Comment by yann300** [comment]
There 's strange behavior when the provider (`Environment`) is changed and `Enter` is pressed.
this way could fix it: 
```
window.onclick = function(event) {
    if (event.target == modal) {
        // cancel dialog
    }
}
```

**Comment by up730418** [comment]
@yann300 would you be able to give me a bit more information on this so i can take a look please. 
Thanks

**Comment by yann300** [comment]
when I switch to `Web3 Provider`, the modal shows up but the focus seems to stay in the dropdown list, when I then press Enter, somehow the `Javascript VM` get selected...

**Comment by up730418** [comment]
Ok. I will take a look at it.

**Comment by up730418** [comment]
Hopefully this should fix the issue you where having

**Comment by yann300** [comment]
Thanks that works better :+1: 
I m not really sure the way the "click outside of the dialog" really works now. If you click on the upper left section of the screen it does not.

**Comment by up730418** [comment]
This should now allow you to click anywhere. 
I also found that the previous change meant sometimes you couldn't type in the dialogue box. This should now be fixed

**Comment by yann300** [comment]
I had to create a new PR. I made a wrong rebase => https://github.com/ethereum/browser-solidity/pull/1066
going to merge thanks!

**Pull request closed without merging**
