### PR TITLE
Fix provider init

### PR DESCRIPTION
**Pull request by yann300**

### CODE REVIEW

**Comment by axic** [comment]
Is this fixing #405?

**Comment by yann300** [comment]
no I don't think so

**Comment by Manidos** [comment]
Hey! I'm not sure if it's related to this merge but since this morning I can't use the compiler with MetaMask, `invalid JSON RPC error`

**Comment by yann300** [comment]
@Manidos please retry

**Comment by Manidos** [comment]
@yann300 , it works! You're a magician, sir!

**Pull request merged**
