### PR TITLE
Fixing styling (caret on instance, abstract contracts title)

### PR DESCRIPTION
**Pull request by ninabreznik**
- [x] carrot on contract instance doesn't change on toggle
- [x] abstract contract title (no bytes) => align right, should be center
- [ ] mimimum size of righthand, lefthand and editor
- [ ] remove multi-scroller

### CODE REVIEW

**Comment by ninabreznik** [comment]
See issue https://github.com/ethereum/browser-solidity/issues/558

**Comment by ninabreznik** [comment]
Didn't use flexbox, but margin left and right so hopefully it looks ok also on bigger screens, mine is 13'' :)

**Comment by yann300** [comment]
can we merge now and continue in the next PR?

**Comment by ninabreznik** [comment]
@yann300 Absolutely! @chriseth even asked to do many PRs.

**Comment by yann300** [comment]
clicking on the `copy address` button also trigger the fold/unfold action (that should just copy).

**Comment by ninabreznik** [comment]
@yann300 Will fix that

**Pull request merged**
