### PR TITLE
Dont display empty compiler output fields

### LINKED ISSUE #155: Don't display empty compiler output fields
Currently, in some cases (abstract contracts, empty contracts) the bytecode or interface fields are empty.

Empty fields probably shouldn't be displayed.

(This may depend on https://github.com/ethereum/solidity/issues/758)

### PR DESCRIPTION
**Pull request by axic**
Fixes #155.

### CODE REVIEW

**Comment by axic** [comment]
@Denton-L here's the other change to make it even more intelligent :)

**Comment by Denton-L** [comment]
One small issue (sorry!), for contract `A` in the following example, I feel like it should display the interface, even though it's only `[]` because `[]` is still a valid interface. But this is just a minor edge-case.

2016-07-28-135832_1366x731_scrot

**Comment by axic** [comment]
> One small issue (sorry!), for contract A in the following example, I feel like it should display the interface, even though it's only [] because [] is still a valid interface.

Not sure how useful that is, but I could be convinced.

**Comment by Denton-L** [comment]
I suppose it's just semantics but if there isn't an interface line displayed, it would imply that `A` does not have an interface at all, which isn't true because all contracts have interfaces, whereas displaying `[]` would tell the user that `A` has an interface, and it's `[]`.

**Pull request merged**
