### PR TITLE
Include a gas limit for web3 constant calls

### PR DESCRIPTION
**Pull request by axic**
Missed this in #124

### CODE REVIEW

**Comment by redsquirrel** [comment]
Just a general question: why would you need to specify (or spend) gas on an `eth_call`?

**Comment by axic** [comment]
@redsquirrel albeit there is no gas being spent on `eth_call`, it can still be used to set a limit on how much time a call take, i.e. to avoid a deadlock on the node, when running an infinite loop in a contract.

**Comment by redsquirrel** [comment]
@axic Really? If you wouldn't mind explaining, how does that work? Does `eth_call` still operate under gas constraints, but just doesn't withdraw the balance?

**Comment by axic** [comment]
@redsquirrel I think it depends on the implementation, but in general it should work like that.

`call` should be able to do (and access) everything a transaction can, except all changes made during the `call` are *ignored*.

During the `call` an `sstore` and subsequent `sload` should work as desired. So either one implements a specific sandbox or just rolls back the changes after.

**Comment by chriseth** [comment]
Shouldn't the gas limit be much higher for a call?

**Comment by axic** [comment]
@chriseth hmm, maybe.

That change belongs to a separate PR in my opinion as the VM mode needs to be changed too. And perhaps the UI as well? Or let us just settle at 10 times the normal gas?

**Pull request merged**
