### PR TITLE
Use formatting according to 'istandard'

### PR DESCRIPTION
**Pull request by axic**
We still need to apply indentation changes and fix some of the bugs found, such as `if (widthOfList() + getLeftPosi() > + widthOfVisible()) {`

cc @redsquirrel @chriseth

### CODE REVIEW

**Comment by redsquirrel** [comment]
I think this formatting would be a great step forward.

**Comment by axic** [comment]
@chriseth rebased

**Comment by redsquirrel** [comment]
Is this going in soon-ish? I'm waiting for it to be merged before starting on some subsequent work, since this touches so many lines.

**Comment by chriseth** [comment]
Sorry, please rebase again. Will try to merge this first.

**Comment by axic** [comment]
@chriseth rebased, but please double check

**Pull request merged**
