### PR TITLE
Static Analysis: Assembly, Checks Effetct Interaction, Constant Functions without modifiers.

### PR DESCRIPTION
**Pull request by soad003**
Saw that is is not automatically mergeable. Is it easier for you if I fork again and re-add my files?

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks for your PR!
Just a short comment: Please rebase instead of merging, github makes it impossible to see what happened in a merge commit.

**Comment by chriseth** [comment]
It also seems that this PR contains quite some commits that were merged in the meantime.

**Comment by soad003** [comment]
Sorry, i am not that experienced when it comes to git workflows. What do you suggest me to do?

**Comment by axic** [comment]
@soad003 you can try `git rebase origin/master` on your branch if the `origin` remote points to this repo.

**Comment by soad003** [comment]
@axic Created a new PR from a new branch. Don't know if that is better?! Please close this one if the other is better.

**Comment by soad003** [comment]
https://github.com/ethereum/browser-solidity/pull/508

**Pull request closed without merging**
