### PR TITLE
Fixing the Delete button bug

### PR DESCRIPTION
**Pull request by redsquirrel**
Fixing #53 and #71 by reverting 0a37e6a

### CODE REVIEW

**Comment by redsquirrel** [comment]
Thanks to @Denton-L for finding the guilty commit!

**Comment by axic** [comment]
Not sure it is relevant, but I've found this typo: https://github.com/ethereum/browser-solidity/pull/68/commits/0b44735763adfbb0ea84a1c5642ccff6d5c68804

**Comment by redsquirrel** [comment]
@axic Nice catch. But I don't think it relates to this issue.

**Comment by Denton-L** [comment]
I've been digging into it and your commit seems to only expose the bug, rather than create it. For some reason, `editor.on` and `editor.getSession` are both undefined. Even in earlier "good" versions, resizing the window will cause a JavaScript error because it's attempting to make a call to something undefined.

I guess this can serve as a band-aid fix for now but at some point, we should figure out what's wrong.

**Comment by redsquirrel** [comment]
The first priority is to fix the bug in the user experience. Next step will be to retry the refactoring and get to the bottom of why it failed.

**Comment by chriseth** [comment]
This seems to be stalled on travise. Can you force-push to retrigger the build?

**Comment by Denton-L** [comment]
If this gets merged in its current state, the tree is going to get dirtied with double commits.

Can you `git reset --hard 0a37e6a3fbcd8be1e09affa6b860bb6d03143941` and then force push to get rid of the double commits?

**Comment by redsquirrel** [comment]
Rebased, with clean commit history

**Comment by redsquirrel** [comment]
@chriseth This fixes a fairly urgent bug (report at #71). Merge soon?

**Comment by Denton-L** [comment]
@redsquirrel, are you going to be resubmitting a fixed version of this commit in the future? I think I discovered the source of the bug.

**Comment by redsquirrel** [comment]
@Denton-L Yes, I had planned to. Want to share the source of the bug? 😄

**Comment by Denton-L** [comment]
Yeah, sorry it's written down somewhere on the whiteboard at the office. I'll send it to you when I get to work.

**Comment by Denton-L** [comment]
In `editor.js`, `this.setNextFile` calls `this.setCacheFile`. Either `setCacheFile` has to lose its call to `utils.fileKey` or `setNextFile` has to wrap its call with `utils.fileNameFromKey`.

**Comment by redsquirrel** [comment]
Got it. Thanks @Denton-L, I'll take a look at that.

**Pull request merged**
