### PR TITLE
Introduce (metadata) publish button

### LINKED ISSUE #362: Include publish button
This will publish the source codes and the metadata on Swarm/IPFS.

It should be placed next to the "Create" button. It should be disabled if the "Create" button is disabled.

### PR DESCRIPTION
**Pull request by axic**
Fixes #362.

### CODE REVIEW

**Comment by axic** [comment]
This doesn't have the actual publishing implementing, but it depends on https://github.com/ethereum/go-ethereum/issues/3523.

**Comment by axic** [comment]
Since this now displays a warning message ("Feature not implemented."), we might as well merge it.

**Comment by chriseth** [comment]
I don't think we should add a button that is not working.

**Comment by axic** [comment]
> I don't think we should add a button that is not working.

Have you seen the Reddit button? 😉

**Comment by axic** [comment]
Added publishing of metadata. Still need to include way to publish sources.

It should also verify that the published hash matches the pre-calculated hash.

**Comment by chriseth** [comment]
What is missing for publishing the source?

**Comment by axic** [comment]
I have improved version I need to push here, after that we should be able to merge it.

**Comment by axic** [comment]
@yann300 @chriseth I think this can be merged

**Pull request merged**
