### PR TITLE
set autoCompile to false by default

### LINKED ISSUE #874: Turn off auto-compile by default
It is really annoying on slower computers.

### PR DESCRIPTION
**Pull request by Zaccc123**
fixes #874

### CODE REVIEW

**Comment by yann300** [comment]
thanks for the PR!
but then tests are failing cause nothing compile by default :)

**Comment by yann300** [comment]
in order to fix test
could you change `test-browser/helpers/init.js` to

```
module.exports = function (browser, callback) {
  browser
    .url('http://127.0.0.1:8080/#version=builtin')
    .injectScript('test-browser/helpers/applytestmode.js', function () {
      browser.click('#autoCompile')
      .perform(function () {
        callback()
      })
    })
}
```

**Comment by Zaccc123** [comment]
Most test passed now, but some got timeout before the `<div>` is found:

```
   Timed out while waiting for element <#editor-container div[class^="terminal"] span[id="tx0x917a873d27d105213eaf5461e14780387ccceb66fed574f8432d1963917832ae"]> to be present for 10000 milliseconds.  - expected "found" but got: "not found"
```

Any idea why or should we try to increase the second?

**Comment by yann300** [comment]
Please try to rebase to master if it's not already done, that might solve the issue.

**Comment by Zaccc123** [comment]
Is already on the latest `master`

**Comment by axic** [comment]
@yann300 anything stopping merging this?

**Pull request merged**
