### PR TITLE
Web3 cleanup

### PR DESCRIPTION
**Pull request by axic**
I'm sure that the first 3 commits are useful, but not sure if @redsquirrel plans to do something with web3 in the upper layers, hence the last commit might or might not be useful.

### CODE REVIEW

**Comment by redsquirrel** [comment]
Don't worry about what I'm planning. I'm still figuring things out. This is a nice refactoring. 👍

**Comment by chriseth** [comment]
Looks good!

**Comment by axic** [comment]
@chriseth rebased

**Comment by axic** [comment]
@chriseth I think I've managed to break it with this one. web3 is needed for ABI encoding.

**Comment by kumavis** [comment]
wasnt abi broken out into a separate module somewhere?

**Comment by axic** [comment]
It only uses ethereumjs-abi for decoding the results. For encoding there's a PR #22 to change from web3.js to ethereumjs-abi.

**Comment by kumavis** [comment]
sweet

**Pull request merged**
