### PR TITLE
Remove Solidity Interface from the output

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by chriseth** [comment]
This also removes it if an older compiler version is selected. Also included this feature here: https://github.com/ethereum/browser-solidity/pull/207

**Comment by axic** [comment]
Yes it does, but is it needed with an older one?

**Comment by chriseth** [comment]
It is not "needed", but we can provide it.

**Comment by axic** [comment]
Wouldn't that be a cause of complaint? (*Why does it work with an older version and not with the latest one?*)

**Comment by chriseth** [comment]
The better argument is probably: We should not provide an incentive to use old, potentially buggy compiler versions.

**Pull request merged**
