### PR TITLE
Fix #110

### LINKED ISSUE #110: Minor Issue: Persistent compiler output after file deletion
## Summary
When an old file is moved or deleted, if a new file takes on the previous name of the old file, all of the old compiler output will be displayed.

## Reproduction
1. Create a file, A.
2. Type something to trigger a compiler error.
3. Move or delete A.
4. Create a new file and call it A.
5. The old compiler errors should be displayed.

### PR DESCRIPTION
**Pull request by Denton-L**
This should fix #110.

### CODE REVIEW

**Comment by chriseth** [comment]
Please rebase, don't use `window.localStorage` anymore and squash into a single commit.

**Comment by redsquirrel** [comment]
All access to window.localStorage has been encapsulated in `src/app/storage.js`.

**Comment by Denton-L** [comment]
Alright, rebase done.

**Comment by Denton-L** [comment]
Sorry for that, I had to restart the stalled build.

**Pull request merged**
