### PR TITLE
remove e6-shim

### PR DESCRIPTION
**Pull request by yann300**
address https://github.com/ethereum/browser-solidity/issues/383

### CODE REVIEW

**Comment by axic** [comment]
@yann300 you need also to remove the `require()` statement in `index.js`

**Comment by axic** [comment]
@yann300 do we have a sauceconnect test browser version which is non-ES6?

**Comment by axic** [comment]
Firefox <50 seems like a good candidate to include in the tests.

**Comment by yann300** [comment]
I'm not sure which is the current firefox version that sauceconnect use. but IE11 is the ie version sc use for testing and it is not es6.
In any case it could make sense to add also Firefox<50

**Comment by axic** [comment]
Would be nice to have both Firefox 49 and >50 as a definitive test case.

**Comment by yann300** [comment]
yes will add a task

**Comment by yann300** [comment]
tests are failing because of

**Pull request merged**
